### ISSUE TITLE
Error: Apparent recursion within a with_prototype action: 25000 context sanity limit hit

### ISSUE THREAD

**Issue by G4Zz0L1** [y0ssar1an/CSS3#107] opened 2018-07-18 10:20 UTC
On sublime 3.1.1 build 3176

With this plugin installed I get:

`Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

If removed it goes away and everything works (except for css, of course)

Edit: reference https://github.com/sublimehq/Packages/issues/1665

**Comment by ninja542** [comment] 2018-07-18 23:14
I have this same problem too, I don't know why it appeared yesterday, before that I didn't have problems with this package

**Comment by theElectricBear** [comment] 2018-07-20 15:33
I can confirm that this issue just started 2 days ago as well

**Comment by G4Zz0L1** [comment] 2018-07-25 07:05
Any news on this?

**Comment by ninja542** [comment] 2018-07-25 20:35
No responses from maintainer, I'm just going to keep the package disabled on my sublime text

Weirdest part is that sublime text and the css3 packages have not changed/updated, but this problem suddenly appeared out of nowhere

reinstalling everything from a fresh sublime text install didn't help either until disabling css3

**Comment by cit-a** [comment] 2018-07-27 17:07
I just had the same problem (not yesterday nor three days before). Disabling CSS3 didn't help me out.
For me it was JavaScriptNext - ES6 Syntax. I've disable it and enable CSS3.
The problem was solved after restarting ST3.

**Comment by y0ssar1an** [comment] 2018-07-30 03:49
Sorry for taking so long to fix this, but it should be fixed now in #108. Version 2.1.18 should be out on Package Control shortly. Please reopen if you continue to see the sanity limit error.

**Comment by G4Zz0L1** [comment] 2018-07-30 08:20
It seems that the error it's still there.

I've tried wiping cache files, and the plugin it's updated to version 2.1.18

**Comment by y0ssar1an** [comment] 2018-07-30 18:54
Very sorry, guys. I'll investigate tonight.

**Comment by G4Zz0L1** [comment] 2018-08-05 12:41
Any news? I really like this plugin, I don't want to remove it...

**Comment by y0ssar1an** [comment] 2018-08-06 01:50
Hmm, I'm not able to reproduce this. I tried several large PHP programs and didn't get any errors. This may be caused by an interaction of plugins.

Can someone please provide some sample code where the issue occurs for them, along with their list of installed packages? Thank you!

**Comment by KristoferN** [comment] 2018-08-10 08:38
This happens to me too. Same error and no syntax highlighting of PHP files when CSS3 package is installed. When i remove the CSS3 package the problem disappears.

Installed packages:
[
		"Alignment",
		"ArcticTypescript",
		"AutoFileName",
		"Autoprefixer",
		"BracketHighlighter",
		"BufferScroll",
		"CSS3",
		"CSScomb",
		"DocBlockr",
		"EditorConfig",
		"Emmet",
		"Go To Definition",
		"HTML-CSS-JS Prettify",
		"JavaScriptNext - ES6 Syntax",
		"jQuery",
		"LESS",
		"Origami",
		"Package Control",
		"PackageResourceViewer",
		"PHP Syntax Checker",
		"Phpcs",
		"Sass",
		"SCSS",
		"SideBarEnhancements",
		"SublimeLinter-phpcs",
		"Terminal",
		"Twig",
		"TypeScript",
		"WordPress"
	]

**Comment by theElectricBear** [comment] 2018-08-10 16:07
@y0ssar1an So strangely, I tried to do a little trouble shooting and disabled all 3rd party plugins that I had installed and turned them back on one by one to see if I could suss out the conflict. This apparently cleared the problem for me. There was some weirdness when I disabled 'Jade' but I cant confirm that this was the source of the conflict.

the plugins I have in common with @KristoferN are:
'CSS3',
'JavaScriptNext - ES6 Syntax',
'Package Control',
'SCSS'

**Comment by ninja542** [comment] 2018-08-11 03:36
Thank you for debugging this package! I think that submitting the issue of increasing the context is a good idea.

**Comment by y0ssar1an** [comment] 2018-08-19 00:03
I opened [an issue to discuss raising the context limit](https://github.com/sublimehq/Packages/issues/1687). It's not gonna happen, for the very good reason that it shouldn't take gigabytes of RAM to edit kilobytes of text. It looks like I made a bad call when I decided to make CSS3 function like a linter by writing regexes for every CSS property. Reversing that design decision would require an extensive rewrite. I don't have time for that, unfortunately.

As a short-term mitigation, I think I will disable CSS3 highlighting inside languages like HTML and PHP. I will no longer recommend disabling the default CSS package in the install notes. Users will have to switch back and forth between CSS and CSS3. That's annoying, but less annoying than this awful error.

**Comment by G4Zz0L1** [comment] 2018-08-21 13:14
This bug it's still present. Even if I don't disable the native CSS plugin, just the fact that this CSS3 plugin is installed pops up the error. What should I do?

**Comment by y0ssar1an** [comment] 2018-08-21 20:27
I'm so sorry. It must be hitting the limit in a way that I don't understand. I don't have time to work on CSS3 at the moment. If anybody wants to help debug this, you can 1) remove CSS3, 2) clone this repo to your Sublime Packages directory, and 3) comment-out parts of `CSS3.sublime-syntax` until the error goes away. Then shrink the number of commented-out lines until you can identify the problem context (syntax highlighting rule). It's almost certainly the `properties` context. I thought I'd fixed the source of errors from that context.

**Comment by tomcon** [comment] 2018-11-01 01:36
Still present - breaks PHP.sublime-syntax. 
Only by removing CSS3 is everything ok again
Seems there is still  a problem with this package

**Comment by y0ssar1an** [comment] 2020-01-28 03:36
I'm working on CSS3 again after a long hiatus. Can anybody tell me if this problem is still occurring? I made a change recently which should've reduced the number of contexts on the stack a little.

**Comment by ninja542** [comment] 2020-01-29 23:16
hi sorry, I think it's still happening, it lists Markdown and CSS as part of context overload?

**Comment by y0ssar1an** [comment] 2020-01-29 23:46
Ok, thanks for letting me know. I used to be able to trigger the error pop-up by opening a PHP file. I can no longer do that. Opening a Markdown file doesn't work either. Can someone list the steps to reproduce the error? Please make sure you're using the latest `CSS3`, v2.1.22. Thanks!

**Comment by ninja542** [comment] 2020-01-30 02:40
hm I have MarkdownEditing just showing context sanity hit limit, and I have a markdown file open

I don't have any CSS files open either, and I closed the previous JSON file I had open

**Comment by y0ssar1an** [comment] 2020-01-30 06:52
Does the problem still occur after upgrading to build 3211?

**Comment by y0ssar1an** [comment] 2020-02-05 02:59
Since I haven't been able to reproduce the bug, and haven't been able to confirm that the problem occurs on the latest Sublime Text build, I will close this issue. I will reopen if anyone out there is still experiencing the issue.

>Weirdest part is that sublime text and the css3 packages have not changed/updated, but this problem suddenly appeared out of nowhere

If the problem is indeed resolved, I wonder if the issue was fixed or worked around in Sublime Text itself 🤔

**Closed by y0ssar1an** 2020-02-05 02:59 UTC
