### ISSUE TITLE
Missing property

### ISSUE THREAD

**Issue by nagman** [y0ssar1an/CSS3#79] opened 2017-06-08 08:18 UTC
Hi,

The `backface-visibility` is not implemented.

Could you do an update?

**Comment by y0ssar1an** [comment] 2017-06-24 18:06
`backface-visibility` is implemented and is working for me. Can you try running a manual update and restarting Sublime?

`Package Control: Upgrade Packages`

Also, make sure the syntax is set to CSS3 and not CSS.
![image](https://user-images.githubusercontent.com/1250684/27510778-20ab8d42-58cd-11e7-8554-0c56e2bd1dde.png)

**Comment by y0ssar1an** [comment] 2017-07-04 20:18
I'm gonna close this, as I can't reproduce the issue. Feel free to add comments if you're still struggling with this issue.

**Closed by y0ssar1an** 2017-07-04 20:18 UTC
