### ISSUE TITLE
Vendor prefixes?

### ISSUE THREAD

**Issue by rafapaulin** [y0ssar1an/CSS3#65] opened 2016-08-15 17:34 UTC
Will this syntax support vendor prefixes?

Thanks!

**Comment by variadico** [comment] 2016-08-15 18:13
By vendor tags, do you mean vendor prefixes?
https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix

**Comment by rafapaulin** [comment] 2016-08-15 18:24
Yes, sorry!

**Comment by y0ssar1an** [comment] 2016-08-15 18:24
Are you asking about vendor prefixes like `-webkit-` and `-moz-`? If so, there are already several that are supported. The lists of `-moz-` and `-ms-` prefixed elements are fairly comprehensive. There are lots of missing `-webkit-` prefixed elements because I couldn't find any authoritative lists of them. If you're aware any such lists, please let me know. If there's some commonly used vendor-prefixed elements that you think are missing, please list them here and I'll investigate.

My criteria for including vendor-prefixed stuff is that it must be on the standards track. In other words, it must be described in a W3C spec. That excludes a lot of browser-specific prefixes.

I should point out that a lot of the vendor-prefixes people _think_ they need are actually totally unnecessary, unless they have to support truly ancient browsers. Those prefixed elements have been intentionally left out.

**Comment by rafapaulin** [comment] 2016-08-15 18:28
Could you, please, provide a example of vendor prefix that your syntax recognize? I am working on a theme of my own, and I could not find the proper scope to any of [-webkit-, -moz-, -o-, -ms-] I tried

**Comment by rafapaulin** [comment] 2016-08-16 13:56
please?

**Comment by variadico** [comment] 2016-08-16 17:08
```css
html {
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    -webkit-appearance: none;
}
```

Found these from normalize.css.

**Comment by y0ssar1an** [comment] 2016-08-16 17:55
I didn't make a separate scope for the vendor prefix. I just included the prefix with the property name, @-rule, etc.

```yaml
# CSS Basic User Interface Module Level 4
property-appearance:
  - match: ((?:-webkit-|-moz-)?\bappearance)\s*(:)
    captures:
      1: support.type.property-name.css
      2: punctuation.separator.key-value.css
```
https://github.com/y0ssar1an/CSS3/blob/develop/CSS3.sublime-syntax#L3609

Does this create any problems for you as a theme maker? If so, I could update the plugin to add a scope to just the `-webkit-`, `-moz-`, and `-ms-` parts.

**Comment by rafapaulin** [comment] 2016-08-16 18:12
Actually, I need the scope to be able to set the format options, otherwise I cant "select" the vendor prefixes. If you could add them, it would be perfect! A "vendor" scope that groups all relevant prefixes is more than enough. Thanks!

Silly question: "-o-" is deprecated/obsolete already?

**Comment by y0ssar1an** [comment] 2016-08-16 18:19
`-o-` became obsolete when the Opera browser switched to the Blink rendering engine in 2013. Blink was a fork of WebKit and used `-webkit-` prefixes. The current version of the Opera browser is 39.

So, yeah, `-o-` is very dead. People are still using it though.

**Comment by rafapaulin** [comment] 2016-08-16 18:41
I see, thanks!

I'll be looking forward the prefixes scope support! Thanks again!

**Comment by WillsB3** [comment] 2016-11-28 16:03
Honestly, if you're still writing vendor prefixes by hand, you probably shouldn't be, as the above discussion shows. The necessary prefixes change as browsers age and draft specs become standard.

Instead, use something like [Autoprefixer](https://github.com/postcss/autoprefixer)

**Comment by selrond** [comment] 2017-02-20 15:31
is there an option to disable autoprefixing?

**Comment by y0ssar1an** [comment] 2017-02-20 18:43
CSS3 doesn't do autoprefixing like, say, Autoprefixer. It will offer some prefixed properties in the completions menu. So if you type `appearance`, for example, `-moz-appearance` and `-webkit-appearance` will be in the completions menu. I researched all the completions in CSS3, so if you see a prefixed property in your completions menu, there's a valid use case for it.

**Comment by selrond** [comment] 2017-02-20 23:30
@y0ssar1an yes sir, and that's what I want to disable, as we have Autoprefixer taking care of all things prefixes.

**Comment by y0ssar1an** [comment] 2017-02-21 00:39
Hmm, I see your point. It would be nice to remove that noise from the completions. It's irrelevant to Autoprefixer users. The problem is that, since not everyone uses Autoprefixer, I'd have to add a config file with a `disable_prefixed_completions` setting. I'm quite proud of the fact that CSS3 currently has "no knobs". I got rid of the the config files in the 2.0 rewrite.

I'm not sure the extra noise in the completions is a big enough problem to add a config file with one setting.

**Comment by y0ssar1an** [comment] 2017-02-21 01:16
[Autoprefixer](https://github.com/postcss/autoprefixer) has improved a lot since CSS3 was first written. I'm considering removing all the prefixed completions and adding some very strong messaging encouraging people to use autoprefixer.

**Comment by selrond** [comment] 2017-02-21 08:15
@y0ssar1an I see your point as well, providing a knobs-free tool which does what it should is great. But the time's moved on since then, and hard-coding prefixes by hand is in my opinion totally unnecessary. Let alone time consuming, unreliable and not future-proof.
Currently I have to delete all the prefixes it creates by hand, as I have Autoprefixer built in my workflow as almost every web developer nowadays, not to say it adds a bit more confusion and makes orientation in the code a little bit harder.

**Comment by y0ssar1an** [comment] 2017-03-06 04:44
With the 2.1.1 release, I've removed completions with vendor-prefixes.

**Closed by y0ssar1an** 2017-03-06 04:44 UTC
Labels: enhancement

**Comment by selrond** [comment] 2017-03-06 08:57
@y0ssar1an Great! However, if I type `df` and hit tab to expand the syntax, it still producses

```css
display: -webkit-flex;
display: -moz-flex;
display: -ms-flex;
display: -o-flex;
display: flex;
```

I'm using correct syntax (CSS3) - where's the problem?

**Comment by y0ssar1an** [comment] 2017-03-06 16:33
I don't think that's coming from CSS3. CSS3 never contained any `-o-` prefixes, and definitely doesn't insert multiple lines like that. I suspected your issue might be caused by another plugin. I still think removing prefixed completions was a good idea.
